### ISSUE TITLE
Xamarin AFMobileSample Android Panic

### ISSUE THREAD

**Issue by infitude** [streetcred-id/agent-framework#79]
**Description**
When trying to run the sample Xamarin AFMobileSample Android project, creating a wallet causes a panic to be thrown and execution stops.

**To Reproduce**
1. Clone the agent-framework repo
2. Build the AFMobileSample solution and deploy the AFMobile.Android project
3. Click on the "CREATE WALLET AND DID" MainPage button
4. In output from debug window, a 'panic' is thrown and execution stops.  No exception is raised in Xamarin

**Expected behavior**
The sample app uses the default external storage location to store the wallet.  

**Screenshots**
Here is the output from the debug window, just after the button is pressed;
```
12-23 00:10:41.290 D/Mono    ( 5943): DllImport loaded library 'libindy.so'.
12-23 00:10:41.290 D/Mono    ( 5943): DllImport searching in: 'indy' ('libindy.so').
12-23 00:10:41.290 D/Mono    ( 5943): Searching for 'indy_create_wallet'.
12-23 00:10:41.290 D/Mono    ( 5943): Probing 'indy_create_wallet'.
12-23 00:10:41.290 D/Mono    ( 5943): Found as 'indy_create_wallet'.
12-23 00:10:41.505 I/Choreographer( 5943): Skipped 901 frames!  The application may be doing too much work on its main thread.
12-23 00:10:48.175 E/log_panics( 5943): thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }': libcore/result.rs:945

```

**Desktop:**
 - Windows 10 1809
 - VS Ent 2019 Version 16.0.0 Preview 1.1

**Smartphone:**
 - Android Emulator (x86_64)

**Additional context**
The sample app has READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE in the AndroidManifest.xml file, MainActivity.cs has ReadExternalStorage and WriteExternalStorage and the UI permissions prompt is responded to with 'Allow'. 

A work around is to provide a StorageConfiguration value in the MainPage, here I'm using the UserProfile storage location; 

```
        async void OnCreateClicked(object sender, EventArgs e)
        {
            ProgressIndicator.IsRunning = true;
            CreateButton.IsEnabled = false;

            WalletConfiguration.WalletStorageConfiguration _storage = new WalletConfiguration.WalletStorageConfiguration { Path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".indy_client") };
            _config.StorageConfiguration = _storage;

            try
            {
                await _walletService.CreateWalletAsync(_config, _creds);
            }
            catch (WalletExistsException)
            {
                //
            }

...
```

**Comment by infitude** [comment]
following on from this, a similar situation occurs when attempting to create a pool.  Here is the modified MainPage code;


```
    public partial class MainPage : ContentPage
    {
        private readonly IPoolService _poolService = App.Container.Resolve<IPoolService>();
        private Pool _pool;

        async void OnCreateClicked(object sender, EventArgs e)
        {
   ...
            try
            {
                var poolGenesisFile = CreateGenesisTxnFile("pool_genesis.txn");
                 await _poolService.CreatePoolAsync("myPool", poolGenesisFile);
            }
            catch (Exception)
            {
            }
           _pool = await _poolService.GetPoolAsync("myPool", 2);
  ...

    public static string CreateGenesisTxnFile(string filename)
        {
            var file = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".indy_client", filename);
            var testPoolIp = "XXX.XXX.XXX.XXX";

            var defaultTxns = new string[]{
   ... 4 nodes ...
             };
            Directory.CreateDirectory(Path.GetDirectoryName(file));
            var stream = new StreamWriter(file);
            foreach (var defaultTxn in defaultTxns)
            {
                stream.WriteLine(defaultTxn);
            }
            stream.Close();
            return file;
        }
```

and the output debug 

```
12-23 01:46:04.322 D/Mono    ( 6367): Searching for 'indy_create_pool_ledger_config'.
12-23 01:46:04.322 D/Mono    ( 6367): Probing 'indy_create_pool_ledger_config'.
12-23 01:46:04.322 D/Mono    ( 6367): Found as 'indy_create_pool_ledger_config'.
12-23 01:46:04.339 E/log_panics( 6367): thread 'unnamed' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }': libcore/result.rs:945

```

**Comment by tmarkovski** [comment]
Thanks for submitting the issue @infitude. It makes sense that creating pool ledger config will fail as well, since they write to the same location, just different folders.

Just to confirm, are you able to write to the directory location using the .NET APIs?

`File.WriteAllText(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".indy_client"), "test");`

@tplooker Any ideas what could be causing this?

**Comment by infitude** [comment]
@tplooker API 27 Android Oreo 8.1 x86_64 Emulator version 27.3.9-4899998 (WHPX 10.0.17763)

**Comment by tplooker** [comment]
@tmarkovski Can you confirm what version we are using for the pre-built binaries for libindy?

**Comment by tmarkovski** [comment]
https://repo.sovrin.org/android/libindy/rc/1.6.8-45/
